### ISSUE TITLE
User Id - 123316 Workouts not count steps, amount

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#148] opened 2020-08-18 09:57 UTC
User Id - 123316 Workouts not count steps, amount and calories.
User name - Aruna
Id - 123316
Version - 2.16.15
Device - Honor JSn l42
![IMG-20200818-WA0000](https://user-images.githubusercontent.com/64827333/90499438-31b44400-e167-11ea-840c-c12889a74a56.jpg)
![IMG-20200818-WA0000](https://user-images.githubusercontent.com/64827333/90499469-3aa51580-e167-11ea-9095-55c9b1a9c70e.jpg)
![IMG-20200818-WA0003](https://user-images.githubusercontent.com/64827333/90499512-4690d780-e167-11ea-866d-e440709c4e38.jpg)
![IMG-20200818-WA0004](https://user-images.githubusercontent.com/64827333/90499553-4f81a900-e167-11ea-8b86-cc2436fa127c.jpg)

**Comment by sagrgpt** [comment] 2020-08-21 08:04
This issue is resolved for v2.16.16 which at the current time is in beta. 
**Please request user to look out for a release soon.** 
**For immediate fix request user to**
1. Long press the app icon on home screen/app drawer
2. Select "App info"
3. Select "App permissions"
4. Allow "Physical Activity" permission.
5. Restart the device.

**Also, this user has battery optimization turned on**. Please **request** user to **set** optimization settings **to** -> **Not Optimized.**

_This issue is a duplicate of issue #68_

**Closed by sagrgpt** 2020-08-21 08:04 UTC
Labels: bug
