### ISSUE TITLE
Flagged workout is counting in daily goal

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#22] opened 2020-05-08 08:53 UTC
Description: I flagged workout of 10 km from ced but still, it's not showing in workout history flagged. Also its counting in the daily goal. Showing text streak maintained but streak count is still 0

**Expected behavior**
Workout should be shown flagged in workout history.
It should not be counted in streak progress.
streak text "streak maintained" should be only shown when streak count increase

![Screenshot_20200508-141025](https://user-images.githubusercontent.com/19950800/81389460-7fb4b700-9137-11ea-8d23-db0cc42acf14.png)
![Screenshot_20200508-141035](https://user-images.githubusercontent.com/19950800/81389467-817e7a80-9137-11ea-8983-8f5e555b732a.png)
![Screenshot_20200508-141041](https://user-images.githubusercontent.com/19950800/81389478-83483e00-9137-11ea-8a9e-c5558b356e37.png)

**Version : 2.14.4.0**

**Additional context**

**Comment by sagrgpt** [comment] 2020-05-11 11:57
Unable to reproduce the issue again. Let's check if this reappears.

**Comment by sagrgpt** [comment] 2020-05-12 14:43
Closing this issue as its not be reproduced anymore.

**Closed by sagrgpt** 2020-05-12 14:43 UTC
Labels: bug
