### ISSUE TITLE
[BUG] Workout notification shows amount but workout screen shows zero

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#135] opened 2020-07-20 13:12 UTC
**Describe the bug**
After an outdoor Workout, if I open the app by clicking on app icon instead of workout notification, it still shows zero while the notification shows correct amount. Also it doesn't update even after waiting for a while on that screen

**To Reproduce**
1. Start an outdoor workout and minimize the app on countdown screen
2. Open the app icon to open the app after your workout
3. Check numbers on workout screen as well as on workout notification

**Expected behavior**
Workout screen should show latest numbers always.

**Screenshots**
![Screenshot_20200720-183545](https://user-images.githubusercontent.com/64794999/87941343-a3419980-cab8-11ea-9f1b-f8fb7b7e40b5.png)
![Screenshot_20200720-183552](https://user-images.githubusercontent.com/64794999/87941347-a472c680-cab8-11ea-9b7e-f08e0f35aa9e.png)

**Version [Check app's setting screen]:**
2.16.9.4

**Additional context**

**Comment by sagrgpt** [comment] 2020-08-05 14:31
I'm unable to reproduce this issue. How frequent is this issue to you?

**Comment by kanakagr** [comment] 2020-08-05 15:10
I haven't done active workout in many days. Will do again and check if it's happening again.

**Comment by sagrgpt** [comment] 2020-08-12 10:12
Closing this issue as it was not reproduceable.

**Closed by sagrgpt** 2020-08-12 10:12 UTC
Labels: bug
