### ISSUE TITLE
Unable to donate passive steps

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#39] opened 2020-05-11 20:07 UTC
**Describe the bug**
When I clicked on donate steps It takes me to the donation screen but there is no cause and if I clicking on the screen then its crashing
**To Reproduce**
Shared video 

**Expected behavior**
If the cause is available then it should show on the donation screen

**Screenshots**
![Screenshot_20200512-013425](https://user-images.githubusercontent.com/19950800/81606562-f03a2d00-93f0-11ea-8007-a94690586de0.png)

**Version:**
2.14.5

**Additional context**

**Comment by sagrgpt** [comment] 2020-05-12 01:08
Closing this issue as it is a duplicate of issue #21. 
@NishantKhandelwal1 we can continue your query (if any) there itself.

**Closed** 2020-05-12 01:08 UTC
Labels: duplicate
