### ISSUE TITLE
[BUG]Not in JLL league but I can't open Teams

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#25] opened 2020-05-08 18:46 UTC
**Describe the bug**
I exited JLL league but I can open teams and the work out button in the home screen is red in color.

**To Reproduce**
1. Go to 'League'
2. Click on 'Exit League'
3. Click 'Teams'

**Screenshots**
![Screenshot_2020-05-09-00-12-02-012_com sharesmile share](https://user-images.githubusercontent.com/64792558/81438334-3d689580-918a-11ea-9f25-dba0b44f635c.jpg)
![Screenshot_2020-05-09-00-12-04-360_com sharesmile share](https://user-images.githubusercontent.com/64792558/81438362-4a858480-918a-11ea-800e-1fb3f12231bb.jpg)
![Screenshot_2020-05-09-00-12-11-652_com sharesmile share](https://user-images.githubusercontent.com/64792558/81438394-540eec80-918a-11ea-9f96-cfc102e99a54.jpg)

**Version [Check app's setting screen]:**2.14.0

**Additional context**

**Comment by adrija25** [comment] 2020-05-08 18:47
Also,it's showing distance covered in the cause card.

**Comment by AnujaPednekar** [comment] 2020-05-11 05:32
Duplicate of I Issue #15

**Closed by AnujaPednekar** 2020-05-11 05:32 UTC
Labels: bug, duplicate
