### ISSUE TITLE
App crashed when clapping from post detail page

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#65] opened 2020-05-14 09:48 UTC
**Describe the bug**
App crashed when clapping from post detail page

**To Reproduce**
Clap any post from post detail page.

**Expected behavior**
It should not crashed

**Screenshots**
Shared video with anuja on slack

**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**

**Comment by 24Kavisha** [comment] 2020-05-14 10:34
+1

**Comment by AnujaPednekar** [comment] 2020-05-14 11:54
Duplicate of Issue #52

**Closed by AnujaPednekar** 2020-05-14 11:54 UTC
Labels: duplicate
