### ISSUE TITLE
App crashing after clapping on any post from post page

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#58] opened 2020-05-14 06:53 UTC
**Describe the bug**
On the post page app crashes after few seconds of clapping

**To Reproduce**
1. Go to any post page inside teams either via notification center or through typical team route
2. Click on clap icon
3. wait for few seconds
4. CRASHhhhh

**Expected behavior**
It should not crashhhhh

**Screenshots**
sending video on slack app_testing channel with this issue link

**Version [Check app's setting screen]:**
2.15.0.0

**Comment by AnujaPednekar** [comment] 2020-05-14 08:53
Duplicate of Issue #52

**Closed by AnujaPednekar** 2020-05-14 08:53 UTC
Labels: bug
