### ISSUE TITLE
[BUG]app crashes when click on send button in post detail page. 

### ISSUE THREAD

**Issue by gauravchauhan677** [Share-Impact/Android-Impact-Issues#64] opened 2020-05-14 09:20 UTC
**Describe the bug**
App get crashes when clicking on send button in post detail page..... While commenting. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Version [Check app's setting screen]:**
Ver. 2.15.0.0

**Additional context**

**Comment by parthanjaria** [comment] 2020-05-14 09:54
Can you share which post you tried to comment on?

**Comment by AnujaPednekar** [comment] 2020-05-14 11:56
Duplicate of Issue #52

**Closed by AnujaPednekar** 2020-05-14 11:56 UTC
Labels: duplicate
