### ISSUE TITLE
[BUG] Exiting from JLL league has issues

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#113] opened 2020-06-22 06:07 UTC
**Describe the bug**
After exiting from JLL league, i see old causes as live and all causes in non impact form i.e. km instead of Rs

**To Reproduce**
1. Join JLL league
2. Exit and see causes
Videos shared on app_testing channel

**Expected behavior**

**Screenshots**

**Version [Check app's setting screen]:**
2.16.5

**Additional context**

**Comment by kanakagr** [comment] 2020-06-24 05:01
I exited from a testing league with special causes and even after exiting, I see league specific causes

**Comment by sagrgpt** [comment] 2020-06-24 08:05
Duplicate of issues #70

**Closed** 2020-06-24 08:06 UTC
Labels: duplicate
