### ISSUE TITLE
User id - 80695 Workout not synced 

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#140] opened 2020-07-27 13:40 UTC
**Describe the bug**
He is facing  Workouts not synced issue. Wrong distance calculation in less time. Sometimes getting less distance, like did 6km but counting 4.1km

**To Reproduce**
1. Go to '.workout history'
2. Click on 'profile

**Expected behavior**
He should get correct distance as per the time

**Screenshots**
![IMG-20200727-WA0013](https://user-images.githubusercontent.com/64827333/88548300-8cf98780-d03c-11ea-8a8a-559bfa455190.jpg)
![IMG-20200727-WA0012](https://user-images.githubusercontent.com/64827333/88548339-984cb300-d03c-11ea-9a15-7edd84b0611a.jpg)
![IMG-20200727-WA0011](https://user-images.githubusercontent.com/64827333/88548398-abf81980-d03c-11ea-8cd2-59f33fd27121.jpg)
![IMG-20200727-WA0010](https://user-images.githubusercontent.com/64827333/88548434-b9ad9f00-d03c-11ea-8dc3-c09f1743953c.jpg)
![IMG-20200727-WA0009](https://user-images.githubusercontent.com/64827333/88548461-c3370700-d03c-11ea-8ea1-618303397879.jpg)

**Version [Check app's setting screen]:**
2.16.9
Redmi Note 8 pro
Anand mulay

**Comment by sagrgpt** [comment] 2020-08-10 09:44
This is a duplicate of issue#134

**Closed by sagrgpt** 2020-08-10 09:44 UTC
Labels: duplicate
