### ISSUE TITLE
[BUG]2 popup coming when not completed 125 steps or 100 m.  To Reproduce

### ISSUE THREAD

**Issue by gauravchauhan677** [Share-Impact/Android-Impact-Issues#21] opened 2020-05-08 08:52 UTC
**Describe the bug**
2 toast coming when not completed 125 steps or 100 m. 

**To Reproduce**
1. Start workout. 
2. Before 125 steps, end workout 125 steps toast come. 
3. Then after 125 steps, end workout. 100m toast came. 

**Expected behavior**
Only one toast should come. 

**Screenshots**

**Version [Check app's setting screen]:**
2.14.4.0

**Comment by sagrgpt** [comment] 2020-05-08 08:58
@gauravchauhan677 Please add proper title to your issues.

**Comment by gauravchauhan677** [comment] 2020-05-08 09:00
Ok

**Comment by sagrgpt** [comment] 2020-05-11 06:06
@gauravchauhan677 Did you start an indoor workout or an outdoor workout when this issue occurred?

**Comment by gauravchauhan677** [comment] 2020-05-11 06:12
> @gauravchauhan677 Did you start an indoor workout or an outdoor workout when this issue occurred?

Indoor workout

**Comment by sagrgpt** [comment] 2020-05-11 07:43
@gauravchauhan677 We have identified and fixed this issue. Please test v2.15.0.0 to assure that this issue is resolved. 
Closing this issue now. You are welcome to re-open the issue is the above mentioned version fail your test.

**Closed by sagrgpt** 2020-05-11 07:43 UTC
Labels: bug
