### ISSUE TITLE
[BUG] Entering into JLL league shows open causes

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#105] opened 2020-06-11 05:51 UTC
**Describe the bug**
Even when I'm in JLL league, I see open causes and supercard

**To Reproduce**
1. Open app, go to league
2. Enter code jlla3
3. Go to Home and see the causes

**Expected behavior**

**Screenshots**
Video shared on #apptesting on slack

**Version [Check app's setting screen]:**
2.16.1

**Additional context**

**Comment by sagrgpt** [comment] 2020-06-11 14:20
Duplicate of issue#70

**Closed** 2020-06-11 14:21 UTC
Labels: duplicate
