### ISSUE TITLE
reduction in number of passive steps [BUG]

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#133] opened 2020-07-17 11:44 UTC
This morning I had work out and I had observed 18000+ steps in Google Fit and Impact, which were perfectly in Sync. But now when I had walk worth of additional 1000+ steps, Impact Application has reversed the count from 18000+ to 2500 steps and I am wondering Why it has deleted 17000+ steps and now Not showing steps as 19000+, same as Google Fit

https://impactapp.freshchat.com/a/154002725929316/inbox/3/0/conversation/313249721684086
https://ced.impactrun.com/userdetail/333920/

**Comment by sagrgpt** [comment] 2020-08-24 12:13
This issue is a duplicate of issue #129

**Closed by sagrgpt** 2020-08-24 12:13 UTC
Labels: duplicate
