### ISSUE TITLE
[BUG] Notification center notifications are read randomly

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#99] opened 2020-06-04 10:56 UTC
**Describe the bug**
Posting this for the 6th time. Some of the badge winning notifications of team in notification center are read and some are unread. I haven't clicked on any.

**To Reproduce**
1. Go to notification center
2. See the notifications

**Expected behavior**
Everything should be highlighted blue if I haven't clicked on any

**Screenshots**
![Screenshot_20200604-162055](https://user-images.githubusercontent.com/64794999/83748643-22514e80-a680-11ea-9ab9-4cdb8a192f08.png)

**Version [Check app's setting screen]:**
2.16.0.2 and all versions before it

**Additional context**

**Comment by sagrgpt** [comment] 2020-06-05 06:30
We noticed that the same issue has already been reported. Please continue on the same thread for faster response.  Duplicate of issue #88

**Closed by sagrgpt** 2020-06-05 06:30 UTC
Labels: duplicate
