### ISSUE TITLE
Incorrect Steps to distance conversion

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#146] opened 2020-08-05 09:22 UTC
https://impactapp.freshchat.com/a/154002725929316/inbox/0/0/conversation/384465280362784

**Comment by sagrgpt** [comment] 2020-08-05 14:12
Description: 
There seems to be some issues with the step counter in the app... It's getting goofed up when I start indoor workout... Also the passive steps are not counted and the collected money is not showing... Please fix it

UserId: 893872
RunId: 49226106

![img_1596618793142](https://user-images.githubusercontent.com/11998999/89422739-57971d00-d753-11ea-8533-1cfb66a00789.jpeg)

**Comment by sagrgpt** [comment] 2020-08-24 09:20
This issue has been resolved for ver 2.16.13. 
Duplicate of issue #134

**Closed by sagrgpt** 2020-08-24 09:20 UTC
Labels: duplicate
