### ISSUE TITLE
[BUG] No post generated in team

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#103] opened 2020-06-08 18:16 UTC
**Describe the bug**
No post generated for 1.1km workout (work out history- or 1.05km as per CED)  and 1 day streak in the team 'Impact official'

**To Reproduce**
You must be used to it by now.

**Expected behavior**
Post kardo bs...ek hi team Mei hu

**Screenshots**
![Screenshot_2020-06-08-23-43-07-080_com sharesmile share](https://user-images.githubusercontent.com/64792558/84065583-38457300-a9e2-11ea-8c1f-30a2c568f1ab.jpg)
![Screenshot_2020-06-08-23-43-14-254_com sharesmile share](https://user-images.githubusercontent.com/64792558/84065586-3aa7cd00-a9e2-11ea-91a1-3946c080e2cb.jpg)
![Screenshot_2020-06-08-23-43-20-047_com sharesmile share](https://user-images.githubusercontent.com/64792558/84065596-3ed3ea80-a9e2-11ea-91b6-65ba899679d6.jpg)

**Version [Check app's setting screen]:**
2.16.0.4

**Additional context**

**Comment by sagrgpt** [comment] 2020-06-10 07:15
@adrija25 We noticed a similar issue has already been previously reported. Closing this issue as a duplicate of issue #71

**Closed by sagrgpt** 2020-06-10 07:15 UTC
Labels: duplicate
