### ISSUE TITLE
[BUG] Home screen showing red start workout button after exiting JLL league 

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#6] opened 2020-05-05 07:47 UTC
**Describe the bug**
I logged in and opened the JLL league, and clicked exit.After exciting, it still showed the red start work out button but the community cause was correct.

Also, total amount raised should reflect in community cause card not distance covered..if I remember correctly.😅

**To Reproduce**
1. Go to 'League'
2. Click on 'Exit league
3. Go to 'Home screen'
4.See error

**Expected behavior**
Could have been due to network issues, if not, it should reflect once you exit league.

**Screenshots**
![Screenshot_2020-05-05-13-00-30-453_com sharesmile share](https://user-images.githubusercontent.com/64792558/81044696-724ac300-8ed2-11ea-90a1-c5aaae9aaeae.jpg)

**Version [Check app's setting screen]:** 2.14.0

**Additional context**
Nil.

**Comment by adrija25** [comment] 2020-05-05 07:50
No wait...should reflect amount raised..😅it's showing total distance in the community cause card as well

**Comment by AnujaPednekar** [comment] 2020-05-11 05:30
Duplicate of Issue #15

**Closed by AnujaPednekar** 2020-05-11 05:30 UTC
Labels: bug, duplicate
