### ISSUE TITLE
[BUG] Streak maintained issue in home page. 

### ISSUE THREAD

**Issue by gauravchauhan677** [Share-Impact/Android-Impact-Issues#11] opened 2020-05-06 04:01 UTC
**Describe the bug**
I covered 0.99km & it show streak maintained in home page. 

**Expected behavior**
Streak maintained should show when completed 1 km. 

**Screenshots**
![IMG_20200505_193908](https://user-images.githubusercontent.com/32591411/81137356-248a9500-8f7c-11ea-964d-7fececf42808.jpg)

**Version [Check app's setting screen]:**
Ver -2.14.3

**Additional context**

**Comment by sagrgpt** [comment] 2020-05-08 06:08
@parthanjaria Is this a repercussion of round off distance value to base instead of celling in the streak manager?

**Comment by parthanjaria** [comment] 2020-05-08 09:30
Yes

**Comment by sagrgpt** [comment] 2020-05-12 07:56
@parthanjaria Please take a look

**Comment by sagrgpt** [comment] 2020-05-13 06:29
@gauravchauhan677 We have identified and fixed this issue. Please test v2.15.0.0 to assure that this issue is resolved.
Closing this issue now. You are welcome to re-open the issue is the above mentioned version fail your test.

**Closed by sagrgpt** 2020-05-13 06:29 UTC
Labels: bug
