### ISSUE TITLE
User Id - 125197 Multiple Workouts

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#141] opened 2020-07-27 13:53 UTC
**Describe the bug*
He is facing issue of multiple workouts and not added Workouts of 28th June. as discussed with Anuja it will be resolved soon.

**To Reproduce**
Steps to reproduce the behaviour
Workout history

**Expected behavior**
Everytime he is facing multiple workouts issues please fix it
**Screenshots**
![IMG-20200726-WA0004](https://user-images.githubusercontent.com/64827333/88549640-2ecda400-d03e-11ea-8052-bd081cd6fd62.jpg)
![IMG-20200726-WA0003](https://user-images.githubusercontent.com/64827333/88549674-39883900-d03e-11ea-90c1-55d22ebcf2d9.jpg)
![IMG-20200726-WA0002](https://user-images.githubusercontent.com/64827333/88549722-49a01880-d03e-11ea-83c5-204b6a6ea088.jpg)
![IMG-20200726-WA0001](https://user-images.githubusercontent.com/64827333/88549767-56247100-d03e-11ea-915a-c965973be4cd.jpg)

**Version [Check app's setting screen]:**
2.16.9
Motorola x4
Moti Singh

**Additional context**

**Comment by AnujaPednekar** [comment] 2020-07-29 13:09
There are two issues:
1. Active workout getting converted to passive ending after 12
2. Multiple passive workouts getting created

**Comment by parthanjaria** [comment] 2020-08-11 06:18
@sagrgpt if multiple workout issue is resolved in the latest build then please close the issue.

**Comment by sagrgpt** [comment] 2020-08-12 10:10
This issue is a duplicate of issue #111

**Closed by sagrgpt** 2020-08-12 10:10 UTC
Labels: Live, bug
