### ISSUE TITLE
[BUG] Incorrect user stats after exiting Non Impact League

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#3] opened 2020-05-04 15:59 UTC
**Describe the bug**
After exiting the league, the steps and km were showing 0 on the 

homepage but differently on streak page.

**Steps To Reproduce**
Exit JLL league
Check homepage stats
Check stats on streak page
Expected behavior
Both screen should show same stats

**Screenshots**
Unable to find attachment option in android app of github
**Video format not supported for attachments**
Adding as ZIP file
[20-05-04-18-10-49.zip](https://github.com/Share-Impact/Android-Impact-Issues/files/4575686/20-05-04-18-10-49.zip)

**Smartphone (please complete the following information):**
Device: [Oneplus 7]
OS: [Android 10]
Version [2.14.0]

Additional context
Add any other context about the problem - here.

**Comment by sagrgpt** [comment] 2020-05-05 04:26
Hi aayush. Please provide proper title gor your issues.

**Comment by sagrgpt** [comment] 2020-05-13 06:30
@gauravchauhan677 We have identified and fixed this issue. Please test **v2.15.0.0** to assure that this issue is resolved.
Closing this issue now. You are welcome to re-open the issue is the above mentioned version fail your test.

**Closed by sagrgpt** 2020-05-13 06:30 UTC
Labels: bug
