### ISSUE TITLE
[BUG] Did not get a +1 red mark when a new feed was put up for JLL

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#85] opened 2020-05-20 05:53 UTC
**Describe the bug**
Did not get a +1 red mark when a new feed was put up for JLL

**To Reproduce**
1. Open the app (you should be in JLL league)
2. See the feed icon 
3. Click to see a new feed put up today

**Expected behavior**
Red mark should come indicating a new feed.

**Screenshots**

**Version [Check app's setting screen]:**
2.15.0

**Additional context**

**Comment by parthanjaria** [comment] 2020-05-22 08:43
The issue is resolved in 2.15.3. Please let us know if the issue still persists

**Closed by parthanjaria** 2020-05-22 08:43 UTC
Labels: bug
